apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "prometheus-aws-discovery.fullname" . }}-configuration
  labels:
    {{- include "prometheus-aws-discovery.labels" . | nindent 6 }}
data:
  config: |
    [profile default]
    {{- if .assumeRole }}
    role_arn = {{ .assumeRole }}
    {{- end }}
    credential_source = Ec2InstanceMetadata
