# -- Does prometheus aws discovery should create the configmap for the discovery results or does it get provided by another tool (e.g. prometheus helm chart)
configmapCreate: true

# -- Name of the configmap, if not overwritten then it will be the helm chart name
#configmapName: ""

# -- Name of the key inside the configmap where the output should be written to
configmapKey: file-sd-config.json

tagprefix: prom/scrape

# -- Schedule for the discovery job to be executed
schedule: "*/5 * * * *"

# -- annotations to be configured on pod level
#podAnnotations:
#  iam.amazonaws.com/role: "prometheus-aws-discovery"

# -- docker image of prometheus aws discovery
image: ghcr.io/daspawnw/prometheus-aws-discovery

# -- docker tag of prometheus aws discovery
tag: 0.7

# -- AWS Region
awsRegion: eu-central-1

# -- Should prometheus-aws-discovery assume a role to execute the discovery
# assumeRole: ""
