{{- if.Values.deployment.imagePullSecretVaultPath }}
apiVersion: "koudingspawn.de/v1"
kind: Vault
metadata:
  name: {{ include "deployment.fullname" . }}-dockercfg
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- include "deployment.backstageLabels" . | nindent 4 }}
spec:
  path: "{{ .Values.deployment.imagePullSecretVaultPath }}"
  type: "DOCKERCFG"
  dockerCfgConfiguration:
    type: "KEYVALUEV2"
{{- end }}