{{- if .Values.serviceAccount.enabled -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "deployment.serviceAccountName" . }}
  labels:
    {{- include "deployment.labels" . | nindent 4 }}
    {{- include "deployment.backstageLabels" . | nindent 4 }}
{{- end }}
